### ISSUE TITLE
Getting a "AEROSPIKE_ERR_NAMESPACE_NOT_FOUND" error

### ISSUE THREAD

**Issue by pushpesh4u** [aerospike/aerospike-client-php#21]
Hello,

I am using Ubuntu 14.04lts.

I have downloaded the latest build. I can see Aerospike in `phpinfo`.

I installed the latest source and tried to run the following:

PHP version - 5.5.9

```
ini_set( 'display_errors', 1 );
ini_set( 'error_reporting', E_ALL );

$config = array(
	"hosts" => array(
		array( "addr" => "localhost", "port" => 3000 )
	)
);

// The new client will connect and learn the cluster layout
$db = new Aerospike( $config );

// failure check
if ( !$db->isConnected() ) {
	echo "Failed to connect to the Aerospike server [{$db->errorno()}]: {$db->error()}\n";
	exit( 1 );
}

$key = $db->initKey( "infosphere", "characters", 1234 );

$put_vals = array("name" => "Scruffy", "Occupation" => "The Janitor");
$status = $db->put($key, $put_vals);

if ($status == Aerospike::OK) {
    echo "Record written.\n";
} elseif ($status == Aerospike::ERR_RECORD_EXISTS) {
    echo "The Aerospike server already has a record with the given key.\n";
} else {
    echo "[{$db->errorno()}] :".$db->error();
}
```

I am getting the below error:

*[20] :AEROSPIKE_ERR_NAMESPACE_NOT_FOUND*

This should just say "Record written".

The page https://github.com/aerospike/aerospike-client-nodejs/blob/master/docs/status.md does not list any error code 20. It should give 501 at least,  which is the error code for the above error.

But, when I test via command line, the getter/setters work.

// setters
cli -h 127.0.0.1 -n test -o set -k Aerospike -b name -v "Aerospike, Inc."
cli -h 127.0.0.1 -n test -o set -k Aerospike -b address -v "Mountain View, CA 94043"
cli -h 127.0.0.1 -n test -o set -k Aerospike -b email -v "info@aerospike.com"

// getters
cli -h 127.0.0.1 -n test -o get -k Aerospike

**Comment by pushpesh4u** [comment]
Not sure why, `rec-operations.php` in the tar is working well.

I have built this same and added aerospike.so to the php.ini file.

Then it doesn't work.

**Comment by rbotzer** [comment]
You need to have the namespace defined in your `/etc/aerospike/aerospike.conf`. In the case of the scripts inside [examples/](https://github.com/aerospike/aerospike-client-php/tree/master/examples) they're all working against the namespace called 'test', which is pre-defined. In the sample code you started with there is probably no namespace named 'infosphere' (sorry, I went all the way with a [Futurama](http://theinfosphere.org) reference there). You should create one.

The operations manual has a section about how to [Configure Aerospike](http://www.aerospike.com/docs/operations/configure/). You want to look at the [Namespace Configuration](http://www.aerospike.com/docs/operations/configure/namespace/) section in particular. Otherwise, change the string 'infosphere' to 'test' in the code you have, and try again.

**Comment by pushpesh4u** [comment]
Yes, figured this out after working on sphinx :). Thanks for confirming it.

**Comment by rbotzer** [comment]
Thanks for giving us the feedback. This has already confused others, so I need to work in a note into that section of the quick guide.

If you run into anything else, please let me know. I appreciate it.
