### ISSUE TITLE
how to query on multiple predicates and how to buffer stream UDF returned value ?

### ISSUE THREAD

**Issue by Abhi11981198** [aerospike/aerospike-client-php#26]
select * from namespace.set where a=somevalue and b=someanothervalue.

what will be the equivalent predicate clause in php client ?

**Comment by Abhi11981198** [comment]
a and b are secondary indices...

**Comment by rbotzer** [comment]
Aerospike clients do not support multiple predicates at the moment. You can either filter on the other value in your application, or do that in a UDF.

Stream UDFs (through the [aggregate()](https://github.com/aerospike/aerospike-client-php/blob/master/doc/aerospike_aggregate.md) method) are already buffered into a single return value, as opposed to [query()](https://github.com/aerospike/aerospike-client-php/blob/master/doc/aerospike_query.md) and [scan()](https://github.com/aerospike/aerospike-client-php/blob/master/doc/aerospike_scan.md) which need you to pass in a callback function.

**Comment by Abhi11981198** [comment]
function get_camp_summary(s, campId)

    local function camp_filter(campId)
        return function(rec)
            if rec['campId'] == campId then
                return true
            end
            return false
        end

    end

    local function camp_map(rec)

        return map{camId = rec['campId'], campName = rec['campName'],Imp = rec['impCount']}

    end

    local my_filter = camp_filter(campId)
    return s : filter(my_filter) : map(camp_map)

end


this is my stream udf which is expected to return multiple records but the return value is : 


array(3) { ["bins"]=> array(3) { ["Imp"]=> int(2) ["campId"]=> string(1) "1" ["campName"]=> string(12) "somecamp" }

**Comment by rbotzer** [comment]
Hi. This is a UDF/Lua specific question, rather than a PHP one. Can you move it to https://discuss.aerospike.com/ please?

Otherwise, please look at the example in the documentation for the [aggregate()](https://github.com/aerospike/aerospike-client-php/blob/master/doc/aerospike_aggregate.md) method. As you can see the aggregation comes back with multiple values. The number of results have to do with your aggregation, but in general a stream UDF doesn't return full rows, it returns a list of values after a running a map/reduce operation on the query results. You can write your Lua to map the key-value pairs you want out of the query.
