### ISSUE TITLE
Memory issue and an invalid callback error

### ISSUE THREAD

**Issue by pushpesh4u** [aerospike/aerospike-client-php#27]
Hello,

**Issue 1:**
```
$db = new Aerospike($config,false);
```
It gives an error below:

```
Invalid callback , no array or string given on line....
```

**Issue 2:**

When I refresh the page a few times, I see a memory exhausted error.
I am getting the below error:

```
Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 679948105 bytes) in /var/www/html/Aerospike.php on line 59
```

Here is the line 59

```
#59 - $this->db = new \Aerospike( $this->config, false );

private $config = array(
	"hosts" => array(
		array( "addr" => "127.0.0.1", "port" => 3000 ) // add multiple arrays for more nodes
	)
);
```
I have not changed any default values. Please let me know why this could be happening.

**Comment by rbotzer** [comment]
What's the context this code is running in? I assume it's a webserver. If so, what's the OS type and version, the webserver type and version, and how is it configured (mod_php, FPM, etc).

For one, you're using non-persistent connections which only make sense for single request processes, such as a short running CLI script. If your code is in a webserver the one process will be taking many requests so you want that second argument to be `true` (its default value).

Otherwise, the code you're quoting will not get anywhere near exceeding the memory limit. Try just running the following (config and connect), and reload the page similarly.

```php
<?php
$config = array( "hosts" => array(
        array( "addr" => "127.0.0.1", "port" => 3000 ) // add multiple arrays for more nodes
    )
);
$db = new aerospike($config);
?>
```

Is this still a problem for you? If so, I definitely need the environment details.
 
Most likely has to do with the rest of the code. Can you quote the rest of the script?

**Comment by pushpesh4u** [comment]
OS - Ubuntu 14.04 LTS
Processor - Intel® Core™ i5-4210U CPU @ 1.70GHz × 4

Server - Apache/2.4.7 (Ubuntu)
mod_php5

I am testing with persistence enabled and will let you know.

**Comment by rbotzer** [comment]
Please update us when you do. If the problem persists please let me see the code you're using. I would need to reproduce the problem.

**Comment by pushpesh4u** [comment]
Not seeing it now. Had fixed some external parameters after which haven't seen this error again so far.

**Comment by rbotzer** [comment]
Okay, thanks for checking. Please reopen it if it reoccurs reliably.
